pool:
  vmImage: 'Ubuntu 16.04'

variables:
  tagName: 'latest'
  imageName: '$(dockerId)/ancorazor:$(tagName)'

steps:
- task: replacetokens@3
  inputs:
    rootDirectory: 'Blog.API/'
    targetFiles: 'appsettings.json'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'warn'
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'
    
- task: Docker@2
  inputs:
    containerRegistry: 'My Docker Hub'
    repository: 'siegrainwong/ancorazor'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: '**/docker-compose.yml'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Docker files'
    publishLocation: 'Container'