pool:
  vmImage: 'Ubuntu 16.04'

variables:
  tagName: '$(Build.BuildNumber)'
  imageName: '$(dockerId)/ancorazor:$(tagName)'

steps:
- task: replacetokens@3
  inputs:
    targetFiles: '**/appsettings.json'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'fail'
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'

- task: Docker@2
  inputs:
    containerRegistry: 'My Docker Hub'
    repository: 'siegrainwong/ancorazor'
    command: 'buildAndPush'
    Dockerfile: 'Dockerfile'
    tags: '$(tagName)'

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: 'build/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: replacetokens@3
  inputs:
    rootDirectory: '$(Build.ArtifactStagingDirectory)'
    targetFiles: '**/docker-compose.yml'
    encoding: 'auto'
    writeBOM: true
    actionOnMissing: 'fail'
    keepToken: false
    tokenPrefix: '#{'
    tokenSuffix: '}#'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'Docker files'
    publishLocation: 'Container'