version: "3.1"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.16
    container_name: elasticsearch
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - docker-network

  skywalking:
    image: wutang/skywalking-docker
    container_name: skywalking
    depends_on:
      - elasticsearch
    ports:
      - 8080:8080
      - 10800:10800
      - 11800:11800
      - 12800:12800
    environment:
      - ES_CLUSTER_NAME=elasticsearch
      - ES_ADDRESSES=http://*:9200

  api:
    image: siegrainwong/blog-api
    build:
      context: ../Blog.API
      dockerfile: Dockerfile
    links:
      - skywalking
    depends_on:
      - skywalking
    ports:
      - 8088:80
    container_name: blog-api

networks:
  docker-network:
    driver: bridge

volumes:
  elasticsearch-data:
